[package]
name = "zero-to-production"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero_to_production"

[dependencies]
actix-web = "4.12.1"
chrono = "0.4.43"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features =  ["postgres", "uuid", "chrono", "migrate", "macros"]}
sqlx-cli = { version = "0.8.6", default-features = false, features = ["postgres"] }
tokio = { version = "1.49.0", features=["rt-multi-thread", "macros"]}
uuid = { version = "1.20.0", features=["v4"]}

[dev-dependencies]
reqwest = "0.13.2"
